# Generated by Django 3.1.5 on 2021-01-11 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KanjiExample',
        ),
        migrations.AddField(
            model_name='paper',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='pub date'),
        ),
        migrations.AddField(
            model_name='score',
            name='paper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='grade.paper'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoredetail',
            name='label',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoredetail',
            name='message',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoredetail',
            name='score',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='grade.score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoredetail',
            name='scoredetail',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
