# Generated by Django 3.1.5 on 2021-01-11 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_auto_20210111_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='img_exp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='img_exp', to='grade.image'),
        ),
        migrations.AddField(
            model_name='score',
            name='img_sq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='img_sq', to='grade.image'),
        ),
    ]
