# Generated by Django 3.1.5 on 2021-01-16 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0007_auto_20210116_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.image'),
        ),
        migrations.AddField(
            model_name='scoredetail',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.image'),
        ),
    ]
