# Generated by Django 3.1.5 on 2021-01-23 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grade', '0008_auto_20210116_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='score_p1',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_p2',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_p3',
        ),
        migrations.RemoveField(
            model_name='scoredetail',
            name='message',
        ),
        migrations.RemoveField(
            model_name='scoredetail',
            name='result',
        ),
        migrations.AddField(
            model_name='scoredetail',
            name='scoredetail',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('index', models.IntegerField(null=True)),
                ('label', models.IntegerField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scoredetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.scoredetail')),
            ],
        ),
    ]
